// user(s) action types
export const REGISTER = "REGISTER";
export const LOGIN = "LOGIN";
export const LOGOUT = "LOGOUT";
export const LOADING = "LOADING";
export const ERROR = "ERROR";
export const LOADING_AVATAR = "LOADING_AVATAR";
export const LOAD_AVATAR = "LOAD_AVATAR";
export const CREATING_USER = "CREATING_USER";
export const ERROR_CREATING_USER = "ERROR_CREATING_USER";
export const CREATE_HOSPITAL = "CREATE_HOSPITAL";
export const GET_ROLES = "GET_ROLES";
export const GET_USERS = "GET_USERS";
export const GET_DOC_LIST_LOADING = "GET_DOC_LIST_LOADING";
export const GET_DOCTORS_LIST = "GET_DOCTORS_LIST";
export const GET_APPROVED_DOCTORS = "GET_APPROVED_DOCTORS";
export const LOADING_APPROVED_DOCTORS = "LOADING_APPROVED_DOCTORS";
export const RESTORE_TOKEN = 'RESTORE_TOKEN'
export const GET_TITLE = 'GET_TITLE'
export const GET_SAVING_EXP = "GET_SAVING_EXP"

// account action types
export const CREATE_ACC_HEAD = "CREATE_ACC_HEAD";
export const CREATE_ACC_HEAD_LOADING = "CREATE_ACC_HEAD_LOADING";
export const GET_ACC_HEAD_LOADING = "GET_ACC_HEAD_LOADING";
export const GET_ACC_HEAD = "GET_ACC_HEAD";
export const GET_REV_ACC_HEAD = "GET_REV_ACC_HEAD";
export const GETTING_TOTAL_SALES_BY_USER = "GETTING_TOTAL_SALES_BY_USER";
export const GET_TOTAL_SALES_BY_USER = "GET_TOTAL_SALES_BY_USER";
export const GET_AMOUNT_RECEIVED = "GET_AMOUNT_RECEIVED";
export const GET_AMOUNT_HANDEDOVER = "GET_AMOUNT_HANDEDOVER";
export const GET_EXPENSES_ACC_HEAD_LOADING = "GET_EXPENSES_ACC_HEAD_LOADING";
export const GET_EXPENSES_ACC_HEAD = "GET_EXPENSES_ACC_HEAD";

// transactions action types
export const GET_GENERAL_ACC_REPORT_LOADING = "GET_GENERAL_ACC_REPORT_LOADING";
export const GET_GENERAL_ACC_REPORT = "GET_GENERAL_ACC_REPORT";
export const GET_EXPENDITURE_ACC_REPORT = "GET_EXPENDITURE_ACC_REPORT";
export const GET_REVENUE_ACC_REPORT = "GET_REVENUE_ACC_REPORT";
export const GET_PATIENT_ACC_STMT = "GET_PATIENT_ACC_STMT";
export const GETTING_PATIENT_ACC_STMT = "GETTING_PATIENT_ACC_STMT";
export const GET_ITEM_HEAD="GET_ITEM_HEAD"
export const NEW_ITEM_DESCRIPTION="NEW_ITEM_DESCRIPTION"
export const GET_ITEM_CHART_TREE="GET_ITEM_CHART_TREE"

// account action types
export const GET_ACC_CHART = "GET_ACC_CHART";
export const GETTING_ACC_CHART = "GETTING_ACC_CHART";
export const GET_ACC_CHART_TREE = "GET_ACC_CHART_TREE";

//shopping types
export const CARTLIST = 'CARTLIST'

// app
export const TOGGLE_MOBILE_VIEW = "TOGGLE_MOBILE_VIEW";
